version: '3'

services:
  client:
    container_name: fast-client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on: 
      - server
  server:
    container_name: fast-server
    build: ./server
    ports:
      - 5000:5000
    environment: 
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - HOST=http://localhost:3000
    volumes: 
      - ./server/src:/app
    depends_on:
      - db
  db:
    container_name: fast-db
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fast
    ports:
      - 3306:3306
    volumes:
      - ./db/fast.sql:/docker-entrypoint-initdb.d/fast.sql
